[project]
name = "comfyui-image-tools"
description = "ComfyUI 图片工具箱 - 图片选择器、图片对比、潜空间生成器、保存图像增强版、性能监控"
version = "1.1.0"
license = "MIT"
dependencies = ["psutil"]

[project.urls]
Repository = "https://github.com/YPuddin-Neko/comfyui-image_tools"

[tool.comfy]
PublisherId = ""
DisplayName = "Image Tools | 图片工具箱"
Icon = ""
